### ISSUE TITLE
Survey admin with no global permissions redirected to plugin page

### ISSUE THREAD

**Issue by alexmarketaccess** [SondagesPro/LS-quickStatAdminParticipationAndStat#1]
If I create a LS survey administrator who has not global permissions except  Use internal database authentication, and I give them full admin permissions to a single survey, when I login as that user, if this plugin is enabled, they are redirected to the plugin page. Then, they cannot access their survey.

I think that correct behaviour for this user type is that they:
1) Shouldn't even have access to this plugin as they aren't super admin
2) They should go to the regular LS dashboard 

![1](https://user-images.githubusercontent.com/15691820/31081646-8746d21a-a75a-11e7-9c96-65365b3b27ae.png)

**Comment by Shnoulle** [comment]
Fixed here : https://github.com/SondagesPro/LS-quickStatAdminParticipationAndStat/commit/e070c882eff8a707333d57c0d00541116c771ba9

Please : report issue on gitlab : https://gitlab.com/SondagesPro/ExportAndStats/quickStatAdminParticipationAndStat/issues if you can.
